name: distrib paratest linux64

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: distrib-${{ github.ref }}
  cancel-in-progress: true
jobs:
  determine-test-directories:
    name: Determine test directories
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/chapel:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      test-dirs-matrix: ${{ steps.determine-test-directories.outputs.test-dirs-matrix }}
      test-dirs-list: ${{ steps.determine-test-directories.outputs.test-dirs-list }}
    steps:
      - name: determine test directories
        run: |
          # use -clean-only to get a list of all test directories without running tests
          # then extract out the directory names that look like `test/something`,
          # then remove the `test/` prefix to get just `something`. ignore subdirs like
          # `test/something/else`.
          $CHPL_HOME/util/start_test $CHPL_HOME/test --clean-only -logfile cleanlog.txt
          cat cleanlog.txt | grep '\[Working on directory' | CWD=`pwd` sed -E "s#\[Working on directory ${CWD}/?(.+)\]#\1#" | grep -E '^test/[^/]+$' | sed -E 's#^test/##' > testdirs.txt

          # Debug: show what directories were found
          echo "Found test directories:"
          cat testdirs.txt

          echo "cleanlog.txt contents:"
          cat cleanlog.txt
      - name: create matrix
        id: determine-test-directories
        run: |
          # Check if testdirs.txt has any content
          if [ ! -s testdirs.txt ]; then
            echo "No test directories found!"
            echo "test-dirs-matrix=[]" >> $GITHUB_OUTPUT
            echo "test-dirs-list=" >> $GITHUB_OUTPUT
            exit 1
          fi

          # create a JSON matrix from the list of test directories
          matrix="[\"$(cat testdirs.txt | tr '\n' ',' | sed -E 's#,$##' | sed -E 's#,#","#g')\"]"
          echo "test-dirs-matrix=$matrix" >> $GITHUB_OUTPUT

          # also output a comma-separated list of test directories for informational purposes
          list=$(cat testdirs.txt | tr '\n' ',' | sed -E 's#,$##')
          echo "test-dirs-list=$list" >> $GITHUB_OUTPUT

          # Debug: show the matrix that was created
          echo "Created matrix: $matrix"

  run-test-dir:
    name: Run tests in directory ${{ matrix.dir }}
    needs: determine-test-directories
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/chapel:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.determine-test-directories.outputs.test-dirs-matrix) }}
    steps:
      - name: run tests
        run: |
          (cd test && $CHPL_HOME/util/test/paratest.local -dirs ${{ matrix.dir }} -logfile "results-${{ matrix.dir }}.txt")

  aggregate-results:
    name: Aggregate results
    needs: [run-test-dir, determine-test-directories]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/chapel:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: aggregate results
        run: |
          echo "Tested directories: ${{ needs.determine-test-directories.outputs.test-dirs-list }}"
          # cat all the individual results files into one big results file
          cat test/results-*.txt > test/aggregated-results.txt
          # TODO: create a better summary of results
      - name: upload results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test/aggregated-results.txt
