name: Weekly Meeting Topics

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 18 * * 2' # Runs every week on Tuesday at 11 PT

jobs:
  check-and-update:
    if: github.repository == 'jabraham17/chapel-ci-testing'
    runs-on: ubuntu-latest

    steps:
    - name: compute date
      id: date
      run: |
        date=$(date -d '+7 days' '+%Y-%m-%d')
        echo "next_meeting_date=$date" >> $GITHUB_ENV
      shell: bash

    - name: create discussion
      run: |
        QUERY='mutation {
          createTeamDiscussion(input: {
            teamId: "T_kwDOLb8lec4CZXIu",
            title: "Chapel project meeting: agenda items for '"${{ env.next_meeting_date }}"'",
            body: $body
          }) {
            teamDiscussion {
              id
              url
            }
          }
        }'
        body=$(jq -n --arg text "${{ env.agenda_body }}" '{$text}')
        gh api graphql -f query="$QUERY" -f body="$body"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          next_meeting_date: ${{ env.next_meeting_date }}
          agenda_body: |
            This discussion is intended as a place for Chapel community members to propose agenda items for the weekly Chapel meeting on ${{ env.next_meeting_date }}.  Potential categories for items include:
            * **News:** Quick updates or announcements to keep people in the loop on key efforts or topics
            * **Demos:** Have something cool to show off?  Do it in a ~5-minute demo
            * **Short Topics:** Have something that needs a quick discussion, description, or straw poll?  Propose a ~5-minute discussion topic
            * **Longer Topics:** Have a more detailed topic you'd like us to try to cover?  Propose the topic and how much time you think it will require and we'll try to fit it in.
            If you'd like to propose an item in any of these categories, please reply to this discussion.
            In addition to the above sections, we have some standing agenda items, such as:
            * **Triage:** What is the state of testing and are there issues that need more attention?
            * **User Issues:** What new user issues have come up in the past week, and which should we prioritize?
            * **Q&A:** Have something you want to ask, but don't think is worth everyone's time?  We'll open the floor to questions as the official meeting wraps up.
            * …  **[your idea here]** …
            To join the meeting, use [this link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_N2M5M2E2NTEtNTFkMi00ZjA1LThiNDQtMjFjY2U2ZDc5ODk3%40thread.v2/0?context=%7b%22Tid%22%3a%22105b2061-b669-4b31-92ac-24d304d195dc%22%2c%22Oid%22%3a%22bef28eea-6179-4f21-b284-84c6a0aeacc3%22%7d)
