name: paratest linux64

on:
  workflow_dispatch:



jobs:
  build-chapel:
    name: Build Chapel
    runs-on: ubuntu-latest
    steps:
    - name: Clone Chapel
      run: |
        git clone https://github.com/chapel-lang/chapel.git --depth 1 --branch main
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc g++ m4 perl python3 python3-dev bash make mawk git pkg-config cmake
        sudo apt-get install llvm-dev llvm clang libclang-dev libclang-cpp-dev libedit-dev

    - name: Build and Install Chapel
      run: |
        mkdir /opt/chapel
        cd chapel
        ./configure --prefix=/opt/chapel
        make -j
        make install
    - name: Verify Chapel installation
      run: |
        export PATH=/opt/chapel/bin:$PATH
        make check
    - name: Save Chapel
      uses: actions/upload-artifact@v3
      with:
        name: chapel
        path: /opt/chapel
  setup-start-test:
    name: Setup start_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run get_start_test
        run: |
          ./get_start_test /opt/start_test
      - name: Add driver script
        run: |
          cp start_test /opt/start_test/start_test
          chmod +x /opt/start_test/start_test
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: start_test
          path: /opt/start_test
  download-tests:
    name: Download tests
    runs-on: ubuntu-latest
    steps:
      - name: Get all Chapel tests
        run: |
          git clone -n --depth=1 --filter=tree:0 -b main --single-branch https://github.com/chapel-lang/chapel.git /opt/tests
          cd /opt/tests
          git sparse-checkout set --no-cone /test
          mv /opt/tests/test/* /opt/tests
          rmdir /opt/tests/test
      - name: Upload tests
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: /opt/tests
  paratest:
    name: Run paratest
    runs-on: ubuntu-latest
    needs: [build-chapel, setup-start-test, download-tests]
    steps:
    - name: Download Chapel
      uses: actions/download-artifact@v3
      with:
        name: chapel
        path: /opt/chapel
    - name: Run paratest
      run: |
        export PATH=/opt/chapel/bin:$PATH
        /opt/start_test/start_test /opt/tests/examples
