name: paratest linux64 OLD

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

concurrency:
  group: paratest1-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-chapel:
    name: Build Chapel
    runs-on: ubuntu-latest
    steps:
    - name: Clone Chapel
      run: |
        git clone https://github.com/chapel-lang/chapel.git --depth 1 --branch main
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gcc g++ m4 perl python3 python3-dev bash make mawk git pkg-config cmake
        sudo apt-get install -y llvm-dev llvm clang libclang-dev libclang-cpp-dev libedit-dev
    - name: Build and Install Chapel
      run: |
        mkdir /opt/chapel
        cd chapel
        ./configure --prefix=/opt/chapel
        make -j`nproc`
        make install
    - name: Verify Chapel installation
      run: |
        cd chapel
        export PATH=/opt/chapel/bin:$PATH
        make check
    - name: Tar
      run: |
        tar -cvf chapel.tar /opt/chapel
    - name: Save Chapel
      uses: actions/upload-artifact@v4
      with:
        name: chapel
        path: chapel.tar
  setup-start-test:
    name: Setup start_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run get_start_test
        run: |
          mkdir -p /opt/start_test
          ./get_start_test.sh /opt/start_test
      - name: Add driver script
        run: |
          cp start_test /opt/start_test/start_test
          chmod +x /opt/start_test/start_test
      - name: Tar
        run: |
          tar -cvf start_test.tar /opt/start_test
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: start_test
          path: start_test.tar

  paratest:
    name: Run paratest
    runs-on: ubuntu-latest
    needs: [build-chapel, setup-start-test]
    steps:
      # TODO: should we just build images instead of this artifact nonsense?
    - name: Download Chapel
      uses: actions/download-artifact@v4
      with:
        name: chapel
        path: chapel.tar
    - name: Extract Chapel
      run: |
        mkdir -p /opt/chapel
        tar -xvf chapel.tar -C /opt/chapel --strip-components=1
    - name: Download start_test
      uses: actions/download-artifact@v4
      with:
        name: start_test
        path: start_test.tar
    - name: Extract start_test
      run: |
        mkdir -p /opt/start_test
        tar -xvf start_test.tar -C /opt/start_test --strip-components=1
    - name: Download tests
      run: |
        mkdir -p /opt/tests
        git clone -n --depth=1 --filter=tree:0 -b main --single-branch https://github.com/chapel-lang/chapel.git /opt/tests
        cd /opt/tests
        git sparse-checkout set --no-cone /test
        git checkout
        mv /opt/tests/test/* /opt/tests
        rm -rf /opt/tests/test
    - name: Run paratest
      run: |
        export PATH=/opt/chapel/bin:$PATH
        /opt/start_test/start_test /opt/tests/examples
