name: paratest linux64

on:
  workflow_dispatch:

concurrency:
  group: paratest-${{ github.ref }}
  cancel-in-progress: true
jobs:
  paratest:
    name: Run paratest
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/chapel:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: run tests
        run: |
          # hack to workaround perl warning
          apt-get purge -y locales
          apt-get install -y locales
          dpkg-reconfigure locales
          $CHPL_HOME/util/start_test $CHPL_HOME/test/release/examples
